### ISSUE TITLE
Hide Notification Content

### ISSUE THREAD

**Issue by yasirtrimulabs** [freshworks/freshchat-ios#130] opened 2021-01-12 15:27 UTC
How to hide the content of the notification like the message from agent? So that the notification only says you have a new notification with out displaying it.

**Comment by MuthuFD** [comment] 2021-01-13 13:01
Duplicate of this [issue](https://github.com/freshworks/freshchat-android/issues/123). Closing this.

**Closed** 2021-01-13 13:05 UTC
