### ISSUE TITLE
Font is altered when message has html tag

### ISSUE THREAD

**Issue by PavelStepanovTomorrow** [freshworks/freshchat-ios#105] opened 2020-05-29 16:03 UTC
Hello!

We have recently found a small issue with font: when there's a html tag in user's or agent's message  the font is altered. You can see it on the screenshot. Compare "F" in the word Font for 2 situations: with and without tag. Or "A" letter in the 2 messages below. One of them has serif.

Side note. In our project, we use only system font, FCTheme file has only system ones as well

Thanks.

<img width="559" alt="Screenshot 2020-05-29 at 17 53 30" src="https://user-images.githubusercontent.com/44771947/83279843-03f9d780-a1d6-11ea-8f92-4df4578e72d3.png">

**Comment by harish-kumarc** [comment] 2020-06-19 14:00
Hi @PavelStepanovTomorrow thanks. We have identified the issue and it happens with iOS 13+devices. We will fix this in our next release(s).

**Comment by harish-kumarc** [comment] 2020-09-29 09:46
Hi @PavelStepanovTomorrow the issue is fixed with SDK release [v3.7.7](https://github.com/freshworks/freshchat-ios/releases/tag/v3.7.7). Please update and let us know.

**Closed by harish-kumarc** 2020-09-29 09:46 UTC
